
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bayu
 */
public class LuasPermukaan extends javax.swing.JFrame {

    /**
     * Creates new form LuasPermukaan
     */
    public LuasPermukaan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        BOLA = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jsisi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jpanjangpp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jlebarpp = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jtinggipp = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jpanjangpi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jlebarpi = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jtinggipi = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jjari = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jpanjangprisma = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jlebarprisma = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jtinggiprisma = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jjari1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jtinggi1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        BOLA1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jsisi1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jpanjangpp1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jlebarpp1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jtinggipp1 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jjari2 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jpanjangprisma1 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jlebarprisma1 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jtinggiprisma1 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jjari3 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();
        jtinggi2 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();

        jButton1.setText("EXIT");

        jLabel1.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel1.setText("VOLUME");

        jLabel2.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel2.setText("PROGRAM PENGHITUNG LUAS, LUAS PERMUKAAN, DAN VOLUME");

        jPanel9.setBackground(new java.awt.Color(153, 255, 255));

        jButton2.setText("VOLUME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("LUAS PERMUKAAN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel1.setLayout(null);

        jLabel3.setText("Cm");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 40, 130, 40);
        jPanel1.add(jsisi);
        jsisi.setBounds(20, 40, 70, 30);

        jLabel4.setText("Masukan panjang sisi");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 10, 130, 40);

        jButton4.setText("Hitung");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(20, 80, 80, 30);

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8);
        jPanel8.setBounds(0, -10, 470, 210);

        BOLA.addTab("KUBUS", jPanel1);

        jPanel2.setLayout(null);

        jLabel5.setText("Cm");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(200, 10, 130, 40);

        jpanjangpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpanjangppActionPerformed(evt);
            }
        });
        jPanel2.add(jpanjangpp);
        jpanjangpp.setBounds(120, 10, 70, 30);

        jLabel6.setText("Masukan panjang :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 10, 130, 40);

        jButton5.setText("Hitung");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(250, 40, 80, 30);

        jLabel15.setText("Cm");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(200, 50, 130, 40);

        jlebarpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlebarppActionPerformed(evt);
            }
        });
        jPanel2.add(jlebarpp);
        jlebarpp.setBounds(120, 50, 70, 30);

        jLabel16.setText("Masukan lebar :");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(20, 50, 130, 40);

        jLabel27.setText("Cm");
        jPanel2.add(jLabel27);
        jLabel27.setBounds(200, 90, 130, 40);

        jtinggipp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtinggippActionPerformed(evt);
            }
        });
        jPanel2.add(jtinggipp);
        jtinggipp.setBounds(120, 90, 70, 30);

        jLabel28.setText("Masukan tinggi :");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(20, 90, 130, 40);

        BOLA.addTab("BALOK", jPanel2);

        jPanel3.setLayout(null);

        jLabel9.setText("Cm");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(200, 10, 130, 40);

        jpanjangpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpanjangpiActionPerformed(evt);
            }
        });
        jPanel3.add(jpanjangpi);
        jpanjangpi.setBounds(120, 10, 70, 30);

        jLabel10.setText("Masukan panjang :");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 10, 130, 40);

        jButton7.setText("Hitung");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);
        jButton7.setBounds(250, 40, 80, 30);

        jLabel29.setText("Cm");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(200, 50, 130, 40);

        jlebarpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlebarpiActionPerformed(evt);
            }
        });
        jPanel3.add(jlebarpi);
        jlebarpi.setBounds(120, 50, 70, 30);

        jLabel30.setText("Masukan lebar :");
        jPanel3.add(jLabel30);
        jLabel30.setBounds(20, 50, 130, 40);

        jLabel31.setText("Cm");
        jPanel3.add(jLabel31);
        jLabel31.setBounds(200, 90, 130, 40);

        jtinggipi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtinggipiActionPerformed(evt);
            }
        });
        jPanel3.add(jtinggipi);
        jtinggipi.setBounds(120, 90, 70, 30);

        jLabel32.setText("Masukan tinggi :");
        jPanel3.add(jLabel32);
        jLabel32.setBounds(20, 90, 130, 40);

        BOLA.addTab("PIRAMID", jPanel3);

        jPanel4.setLayout(null);

        jLabel13.setText("Cm");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(100, 40, 130, 40);
        jPanel4.add(jjari);
        jjari.setBounds(20, 40, 70, 30);

        jLabel14.setText("Masukan panjang jari - jari");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(20, 10, 140, 40);

        jButton9.setText("Hitung");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton9);
        jButton9.setBounds(20, 80, 80, 30);

        BOLA.addTab("BOLA", jPanel4);

        jPanel5.setLayout(null);

        jLabel11.setText("Cm");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(200, 10, 130, 40);

        jpanjangprisma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpanjangprismaActionPerformed(evt);
            }
        });
        jPanel5.add(jpanjangprisma);
        jpanjangprisma.setBounds(120, 10, 70, 30);

        jLabel12.setText("Masukan panjang :");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(20, 10, 130, 40);

        jButton8.setText("Hitung");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8);
        jButton8.setBounds(250, 40, 80, 30);

        jLabel33.setText("Cm");
        jPanel5.add(jLabel33);
        jLabel33.setBounds(200, 50, 130, 40);

        jlebarprisma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlebarprismaActionPerformed(evt);
            }
        });
        jPanel5.add(jlebarprisma);
        jlebarprisma.setBounds(120, 50, 70, 30);

        jLabel34.setText("Masukan lebar :");
        jPanel5.add(jLabel34);
        jLabel34.setBounds(20, 50, 130, 40);

        jLabel35.setText("Cm");
        jPanel5.add(jLabel35);
        jLabel35.setBounds(200, 90, 130, 40);

        jtinggiprisma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtinggiprismaActionPerformed(evt);
            }
        });
        jPanel5.add(jtinggiprisma);
        jtinggiprisma.setBounds(120, 90, 70, 30);

        jLabel36.setText("Masukan tinggi :");
        jPanel5.add(jLabel36);
        jLabel36.setBounds(20, 90, 130, 40);

        BOLA.addTab("PRISMA SEGITIGA", jPanel5);

        jPanel6.setLayout(null);

        jLabel23.setText("Cm");
        jPanel6.add(jLabel23);
        jLabel23.setBounds(200, 10, 130, 40);

        jjari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjari1ActionPerformed(evt);
            }
        });
        jPanel6.add(jjari1);
        jjari1.setBounds(120, 10, 70, 30);

        jLabel24.setText("Masukan jari jari :");
        jPanel6.add(jLabel24);
        jLabel24.setBounds(10, 10, 130, 40);

        jButton11.setText("Hitung");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton11);
        jButton11.setBounds(250, 40, 80, 30);

        jLabel25.setText("Cm");
        jPanel6.add(jLabel25);
        jLabel25.setBounds(200, 50, 130, 40);

        jtinggi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtinggi1ActionPerformed(evt);
            }
        });
        jPanel6.add(jtinggi1);
        jtinggi1.setBounds(120, 50, 70, 30);

        jLabel26.setText("Masukan tinggi :");
        jPanel6.add(jLabel26);
        jLabel26.setBounds(10, 50, 130, 40);

        BOLA.addTab("TABUNG", jPanel6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel7.setText("LUAS PERMUKAAN");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(180, 40, 130, 40);

        jLabel8.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel8.setText("PROGRAM PENGHITUNG LUAS, LUAS PERMUKAAN, DAN VOLUME");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 10, 400, 50);

        jPanel10.setBackground(new java.awt.Color(153, 255, 255));

        jButton10.setText("VOLUME");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton12.setText("LUAS ");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton6.setText("EXIT");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel10);
        jPanel10.setBounds(0, 240, 470, 100);

        jPanel7.setLayout(null);

        jLabel17.setText("Cm");
        jPanel7.add(jLabel17);
        jLabel17.setBounds(100, 40, 130, 40);

        jsisi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsisi1ActionPerformed(evt);
            }
        });
        jPanel7.add(jsisi1);
        jsisi1.setBounds(20, 40, 70, 30);

        jLabel18.setText("Masukan panjang sisi");
        jPanel7.add(jLabel18);
        jLabel18.setBounds(20, 10, 130, 40);

        jButton13.setText("Hitung");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton13);
        jButton13.setBounds(20, 80, 80, 30);

        jPanel11.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel11);
        jPanel11.setBounds(0, -10, 470, 210);

        BOLA1.addTab("KUBUS", jPanel7);

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));
        jPanel12.setLayout(null);

        jLabel19.setText("Cm");
        jPanel12.add(jLabel19);
        jLabel19.setBounds(200, 10, 130, 40);

        jpanjangpp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpanjangpp1ActionPerformed(evt);
            }
        });
        jPanel12.add(jpanjangpp1);
        jpanjangpp1.setBounds(120, 10, 70, 30);

        jLabel20.setText("Masukan panjang :");
        jPanel12.add(jLabel20);
        jLabel20.setBounds(20, 10, 130, 40);

        jButton14.setText("Hitung");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton14);
        jButton14.setBounds(250, 40, 80, 30);

        jLabel21.setText("Cm");
        jPanel12.add(jLabel21);
        jLabel21.setBounds(200, 50, 130, 40);

        jlebarpp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlebarpp1ActionPerformed(evt);
            }
        });
        jPanel12.add(jlebarpp1);
        jlebarpp1.setBounds(120, 50, 70, 30);

        jLabel22.setText("Masukan lebar :");
        jPanel12.add(jLabel22);
        jLabel22.setBounds(20, 50, 130, 40);

        jLabel37.setText("Cm");
        jPanel12.add(jLabel37);
        jLabel37.setBounds(200, 90, 130, 40);

        jtinggipp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtinggipp1ActionPerformed(evt);
            }
        });
        jPanel12.add(jtinggipp1);
        jtinggipp1.setBounds(120, 90, 70, 30);

        jLabel38.setText("Masukan tinggi :");
        jPanel12.add(jLabel38);
        jLabel38.setBounds(20, 90, 130, 40);

        BOLA1.addTab("BALOK", jPanel12);

        jPanel14.setBackground(new java.awt.Color(255, 204, 204));
        jPanel14.setLayout(null);

        jLabel45.setText("Cm");
        jPanel14.add(jLabel45);
        jLabel45.setBounds(100, 40, 130, 40);
        jPanel14.add(jjari2);
        jjari2.setBounds(20, 40, 70, 30);

        jLabel46.setText("Masukan panjang jari - jari");
        jPanel14.add(jLabel46);
        jLabel46.setBounds(20, 10, 220, 40);

        jButton16.setText("Hitung");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton16);
        jButton16.setBounds(20, 80, 80, 30);

        BOLA1.addTab("BOLA", jPanel14);

        jPanel15.setBackground(new java.awt.Color(204, 255, 204));
        jPanel15.setLayout(null);

        jLabel47.setText("Cm");
        jPanel15.add(jLabel47);
        jLabel47.setBounds(240, 10, 30, 40);

        jpanjangprisma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpanjangprisma1ActionPerformed(evt);
            }
        });
        jPanel15.add(jpanjangprisma1);
        jpanjangprisma1.setBounds(160, 10, 70, 30);

        jLabel48.setText("Masukan alas :");
        jPanel15.add(jLabel48);
        jLabel48.setBounds(20, 10, 130, 40);

        jlebarprisma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlebarprisma1ActionPerformed(evt);
            }
        });
        jPanel15.add(jlebarprisma1);
        jlebarprisma1.setBounds(160, 50, 70, 30);

        jLabel50.setText("Masukan tinggi :");
        jPanel15.add(jLabel50);
        jLabel50.setBounds(20, 50, 130, 40);

        jLabel51.setText("Cm");
        jPanel15.add(jLabel51);
        jLabel51.setBounds(240, 90, 130, 40);

        jtinggiprisma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtinggiprisma1ActionPerformed(evt);
            }
        });
        jPanel15.add(jtinggiprisma1);
        jtinggiprisma1.setBounds(160, 90, 70, 30);

        jLabel52.setText("Masukan tinggi prisma :");
        jPanel15.add(jLabel52);
        jLabel52.setBounds(20, 90, 150, 40);

        jLabel57.setText("Cm");
        jPanel15.add(jLabel57);
        jLabel57.setBounds(240, 50, 20, 40);

        jButton17.setText("Hitung");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton17);
        jButton17.setBounds(310, 50, 80, 30);

        BOLA1.addTab("PRISMA SEGITIGA", jPanel15);

        jPanel16.setBackground(new java.awt.Color(255, 255, 204));
        jPanel16.setLayout(null);

        jLabel53.setText("Cm");
        jPanel16.add(jLabel53);
        jLabel53.setBounds(200, 10, 130, 40);

        jjari3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjari3ActionPerformed(evt);
            }
        });
        jPanel16.add(jjari3);
        jjari3.setBounds(120, 10, 70, 30);

        jLabel54.setText("Masukan jari jari :");
        jPanel16.add(jLabel54);
        jLabel54.setBounds(10, 10, 130, 40);

        jButton18.setText("Hitung");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton18);
        jButton18.setBounds(250, 40, 80, 30);

        jLabel55.setText("Cm");
        jPanel16.add(jLabel55);
        jLabel55.setBounds(200, 50, 130, 40);

        jtinggi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtinggi2ActionPerformed(evt);
            }
        });
        jPanel16.add(jtinggi2);
        jtinggi2.setBounds(120, 50, 70, 30);

        jLabel56.setText("Masukan tinggi :");
        jPanel16.add(jLabel56);
        jLabel56.setBounds(10, 50, 130, 40);

        BOLA1.addTab("TABUNG", jPanel16);

        getContentPane().add(BOLA1);
        BOLA1.setBounds(0, 80, 460, 170);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Volume ().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Volume ().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int sisi;
        sisi=Integer.parseInt(jsisi.getText());
        int hasil=sisi*sisi*sisi;
        try {
            JOptionPane.showMessageDialog(null,"Luas persegi adalah :"+hasil,"luas",
                JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :"+e,"gagal",
                JOptionPane.WARNING_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jpanjangppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpanjangppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpanjangppActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int pjg,lbr,tinggi;
        pjg=Integer.parseInt(jpanjangpp.getText());
        lbr=Integer.parseInt(jlebarpp.getText());
        tinggi=Integer.parseInt(jtinggipp.getText());
        int hasil=pjg*lbr*tinggi;
        try {
            JOptionPane.showMessageDialog(null,"Volume Balok Adalah :"+hasil,"luas",
                JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :"+e,"gagal",
                JOptionPane.WARNING_MESSAGE);
        }             // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jlebarppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlebarppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlebarppActionPerformed

    private void jtinggippActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtinggippActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtinggippActionPerformed

    private void jpanjangpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpanjangpiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpanjangpiActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        float panjang,lebar,tinggi;
        panjang=Integer.parseInt(jpanjangpi.getText());
        lebar=Integer.parseInt(jlebarpi.getText());
        tinggi=Integer.parseInt(jtinggipi.getText());
        float hasil=(float) (panjang*lebar*tinggi/3);
        try {
            JOptionPane.showMessageDialog(null,"Volume Piramid Adalah :"+hasil,"luas",
                JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :"+e,"gagal",
                JOptionPane.WARNING_MESSAGE);
        }            // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jlebarpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlebarpiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlebarpiActionPerformed

    private void jtinggipiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtinggipiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtinggipiActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        float jari;
        jari=Integer.parseInt(jjari.getText());
        float hasil=(float) (4/3*3.14*jari*jari);
        try {
            JOptionPane.showMessageDialog(null,"Volume Bola Adalah :"+hasil,"luas",
                JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :"+e,"gagal",
                JOptionPane.WARNING_MESSAGE);
        }       // TODO         // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jpanjangprismaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpanjangprismaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpanjangprismaActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        float panjang,lebar,tinggi;
        panjang=Integer.parseInt(jpanjangprisma.getText());
        lebar=Integer.parseInt(jlebarprisma.getText());
        tinggi=Integer.parseInt(jtinggiprisma.getText());
        float hasil=(float) (panjang*lebar*tinggi/2);
        try {
            JOptionPane.showMessageDialog(null,"Volume Prisma Adalah :"+hasil,"luas",
                JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :"+e,"gagal",
                JOptionPane.WARNING_MESSAGE);
        }                  // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jlebarprismaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlebarprismaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlebarprismaActionPerformed

    private void jtinggiprismaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtinggiprismaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtinggiprismaActionPerformed

    private void jjari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjari1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jjari1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        float jari,tinggi;

        jari=Integer.parseInt(jjari1.getText());
        tinggi=Integer.parseInt(jtinggi1.getText());
        float hasil=(float) (3.14*jari*jari*tinggi);
        try {
            JOptionPane.showMessageDialog(null,"Volume Prisma Adalah :"+hasil,"luas",
                JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :"+e,"gagal",
                JOptionPane.WARNING_MESSAGE);
        }                    // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jtinggi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtinggi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtinggi1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        new Volume ().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        new Luas ().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jtinggi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtinggi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtinggi2ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        float jari,tinggi;

        jari=Integer.parseInt(jjari3.getText());
        tinggi=Integer.parseInt(jtinggi2.getText());
        float a = (float) (3.14*jari*jari*2);
        float b = (float) (3.14*2*jari*tinggi);
        float hasil=(float) (a+b);
        try {
            JOptionPane.showMessageDialog(null,"Volume Prisma Adalah :"+hasil,"luas",
                JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :"+e,"gagal",
                JOptionPane.WARNING_MESSAGE);
        }                    // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jjari3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjari3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jjari3ActionPerformed

    private void jtinggiprisma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtinggiprisma1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtinggiprisma1ActionPerformed

    private void jlebarprisma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlebarprisma1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlebarprisma1ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        float alas,tinggi,tp;
        alas=Integer.parseInt(jpanjangprisma1.getText());
        tinggi=Integer.parseInt(jlebarprisma1.getText());
        tp=Integer.parseInt(jtinggiprisma1.getText());
        float a = (float) (alas*tinggi);
        float b = (float) (alas*tp*3);
        float hasil=(float) (a+b);
        try {
            JOptionPane.showMessageDialog(null,"Luas permukaan prisma Adalah :"+hasil,"luas",
                JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :"+e,"gagal",
                JOptionPane.WARNING_MESSAGE);
        }                  // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jpanjangprisma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpanjangprisma1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpanjangprisma1ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        float jari;
        jari=Integer.parseInt(jjari2.getText());
        float hasil=(float) (4*3.14*jari*jari);
        try {
            JOptionPane.showMessageDialog(null,"Luas Permukaan Bola Adalah :"+hasil,"luas",
                JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :"+e,"gagal",
                JOptionPane.WARNING_MESSAGE);
        }       // TODO         // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jtinggipp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtinggipp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtinggipp1ActionPerformed

    private void jlebarpp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlebarpp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlebarpp1ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        float panjang,lebar,tinggi;
        panjang=Integer.parseInt(jpanjangpp1.getText());
        lebar=Integer.parseInt(jlebarpp1.getText());
        tinggi=Integer.parseInt(jtinggipp1.getText());
        float a = (float) (panjang*lebar*2);
        float b = (float) (lebar*tinggi*2);
        float c = (float) (panjang*tinggi*2);
        float hasil=(float) (a+b+c);
        try {
            JOptionPane.showMessageDialog(null,"Luas Permukaan Balok Adalah :"+hasil,"luas",
                JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :"+e,"gagal",
                JOptionPane.WARNING_MESSAGE);
        }                 // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jpanjangpp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpanjangpp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpanjangpp1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        float sisi;
        sisi=Integer.parseInt(jsisi1.getText());
        float hasil=(float) (sisi*sisi*6);
        try {
            JOptionPane.showMessageDialog(null,"Luas permukaan Adalah :"+hasil,"luas permukaan",
                JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :"+e,"gagal",
                JOptionPane.WARNING_MESSAGE);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jsisi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsisi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsisi1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LuasPermukaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LuasPermukaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LuasPermukaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LuasPermukaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LuasPermukaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane BOLA;
    private javax.swing.JTabbedPane BOLA1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jjari;
    private javax.swing.JTextField jjari1;
    private javax.swing.JTextField jjari2;
    private javax.swing.JTextField jjari3;
    private javax.swing.JTextField jlebarpi;
    private javax.swing.JTextField jlebarpp;
    private javax.swing.JTextField jlebarpp1;
    private javax.swing.JTextField jlebarprisma;
    private javax.swing.JTextField jlebarprisma1;
    private javax.swing.JTextField jpanjangpi;
    private javax.swing.JTextField jpanjangpp;
    private javax.swing.JTextField jpanjangpp1;
    private javax.swing.JTextField jpanjangprisma;
    private javax.swing.JTextField jpanjangprisma1;
    private javax.swing.JTextField jsisi;
    private javax.swing.JTextField jsisi1;
    private javax.swing.JTextField jtinggi1;
    private javax.swing.JTextField jtinggi2;
    private javax.swing.JTextField jtinggipi;
    private javax.swing.JTextField jtinggipp;
    private javax.swing.JTextField jtinggipp1;
    private javax.swing.JTextField jtinggiprisma;
    private javax.swing.JTextField jtinggiprisma1;
    // End of variables declaration//GEN-END:variables
}
