
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bayu
 */
public class Volume extends javax.swing.JFrame {

    /**
     * Creates new form Volume
     */
    public Volume() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BOLA = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jsisi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jpanjangpp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jlebarpp = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jtinggipp = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jpanjangpi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jlebarpi = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jtinggipi = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jjari = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jpanjangprisma = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jlebarprisma = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jtinggiprisma = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jjari1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jtinggi1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setText("Cm");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 40, 130, 40);
        jPanel1.add(jsisi);
        jsisi.setBounds(20, 40, 70, 30);

        jLabel4.setText("Masukan panjang sisi");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 10, 130, 40);

        jButton4.setText("Hitung");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(20, 80, 80, 30);

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8);
        jPanel8.setBounds(0, -10, 470, 210);

        BOLA.addTab("KUBUS", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(null);

        jLabel5.setText("Cm");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(200, 10, 130, 40);

        jpanjangpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpanjangppActionPerformed(evt);
            }
        });
        jPanel2.add(jpanjangpp);
        jpanjangpp.setBounds(120, 10, 70, 30);

        jLabel6.setText("Masukan panjang :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 10, 130, 40);

        jButton5.setText("Hitung");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(250, 40, 80, 30);

        jLabel15.setText("Cm");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(200, 50, 130, 40);

        jlebarpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlebarppActionPerformed(evt);
            }
        });
        jPanel2.add(jlebarpp);
        jlebarpp.setBounds(120, 50, 70, 30);

        jLabel16.setText("Masukan lebar :");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(20, 50, 130, 40);

        jLabel27.setText("Cm");
        jPanel2.add(jLabel27);
        jLabel27.setBounds(200, 90, 130, 40);

        jtinggipp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtinggippActionPerformed(evt);
            }
        });
        jPanel2.add(jtinggipp);
        jtinggipp.setBounds(120, 90, 70, 30);

        jLabel28.setText("Masukan tinggi :");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(20, 90, 130, 40);

        BOLA.addTab("BALOK", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setLayout(null);

        jLabel9.setText("Cm");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(200, 10, 130, 40);

        jpanjangpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpanjangpiActionPerformed(evt);
            }
        });
        jPanel3.add(jpanjangpi);
        jpanjangpi.setBounds(120, 10, 70, 30);

        jLabel10.setText("Masukan panjang :");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 10, 130, 40);

        jButton7.setText("Hitung");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);
        jButton7.setBounds(250, 40, 80, 30);

        jLabel29.setText("Cm");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(200, 50, 130, 40);

        jlebarpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlebarpiActionPerformed(evt);
            }
        });
        jPanel3.add(jlebarpi);
        jlebarpi.setBounds(120, 50, 70, 30);

        jLabel30.setText("Masukan lebar :");
        jPanel3.add(jLabel30);
        jLabel30.setBounds(20, 50, 130, 40);

        jLabel31.setText("Cm");
        jPanel3.add(jLabel31);
        jLabel31.setBounds(200, 90, 130, 40);

        jtinggipi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtinggipiActionPerformed(evt);
            }
        });
        jPanel3.add(jtinggipi);
        jtinggipi.setBounds(120, 90, 70, 30);

        jLabel32.setText("Masukan tinggi :");
        jPanel3.add(jLabel32);
        jLabel32.setBounds(20, 90, 130, 40);

        BOLA.addTab("PIRAMID", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setLayout(null);

        jLabel13.setText("Cm");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(100, 40, 130, 40);
        jPanel4.add(jjari);
        jjari.setBounds(20, 40, 70, 30);

        jLabel14.setText("Masukan panjang jari - jari");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(20, 10, 250, 40);

        jButton9.setText("Hitung");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton9);
        jButton9.setBounds(20, 80, 80, 30);

        BOLA.addTab("BOLA", jPanel4);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(null);

        jLabel11.setText("Cm");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(250, 10, 130, 40);

        jpanjangprisma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpanjangprismaActionPerformed(evt);
            }
        });
        jPanel5.add(jpanjangprisma);
        jpanjangprisma.setBounds(170, 10, 70, 30);

        jLabel12.setText("Masukan alas :");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(20, 10, 130, 40);

        jButton8.setText("Hitung");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8);
        jButton8.setBounds(300, 40, 80, 30);

        jLabel33.setText("Cm");
        jPanel5.add(jLabel33);
        jLabel33.setBounds(250, 50, 130, 40);

        jlebarprisma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlebarprismaActionPerformed(evt);
            }
        });
        jPanel5.add(jlebarprisma);
        jlebarprisma.setBounds(170, 50, 70, 30);

        jLabel34.setText("Masukan tinggi :");
        jPanel5.add(jLabel34);
        jLabel34.setBounds(20, 50, 130, 40);

        jLabel35.setText("Cm");
        jPanel5.add(jLabel35);
        jLabel35.setBounds(250, 90, 130, 40);

        jtinggiprisma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtinggiprismaActionPerformed(evt);
            }
        });
        jPanel5.add(jtinggiprisma);
        jtinggiprisma.setBounds(170, 90, 70, 30);

        jLabel36.setText("Masukan tinggi prisma :");
        jPanel5.add(jLabel36);
        jLabel36.setBounds(20, 90, 150, 40);

        BOLA.addTab("PRISMA SEGITIGA", jPanel5);

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setLayout(null);

        jLabel23.setText("Cm");
        jPanel6.add(jLabel23);
        jLabel23.setBounds(200, 10, 130, 40);

        jjari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjari1ActionPerformed(evt);
            }
        });
        jPanel6.add(jjari1);
        jjari1.setBounds(120, 10, 70, 30);

        jLabel24.setText("Masukan jari jari :");
        jPanel6.add(jLabel24);
        jLabel24.setBounds(10, 10, 130, 40);

        jButton11.setText("Hitung");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton11);
        jButton11.setBounds(250, 40, 80, 30);

        jLabel25.setText("Cm");
        jPanel6.add(jLabel25);
        jLabel25.setBounds(200, 50, 130, 40);

        jtinggi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtinggi1ActionPerformed(evt);
            }
        });
        jPanel6.add(jtinggi1);
        jtinggi1.setBounds(120, 50, 70, 30);

        jLabel26.setText("Masukan tinggi :");
        jPanel6.add(jLabel26);
        jLabel26.setBounds(10, 50, 130, 40);

        BOLA.addTab("TABUNG", jPanel6);

        jLabel1.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel1.setText("VOLUME");

        jLabel2.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel2.setText("PROGRAM PENGHITUNG LUAS, LUAS PERMUKAAN, DAN VOLUME");

        jPanel9.setBackground(new java.awt.Color(153, 255, 255));

        jButton2.setText("VOLUME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setText("LUAS PERMUKAAN");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(147, 147, 147)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(163, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                    .addContainerGap(31, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BOLA, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(180, 180, 180)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(160, 160, 160)
                                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(BOLA, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int sisi;
        sisi=Integer.parseInt(jsisi.getText());
        int hasil=sisi*sisi*sisi;
        try {
            JOptionPane.showMessageDialog(null,"Volume kubus adalah :"+hasil,"volume",
                JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :"+e,"gagal",
                JOptionPane.WARNING_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jpanjangppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpanjangppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpanjangppActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int pjg,lbr,tinggi;
        pjg=Integer.parseInt(jpanjangpp.getText());
        lbr=Integer.parseInt(jlebarpp.getText());
        tinggi=Integer.parseInt(jtinggipp.getText());
        int hasil=pjg*lbr*tinggi;
        try {
            JOptionPane.showMessageDialog(null,"Volume Balok Adalah :"+hasil,"volume",
                JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :"+e,"gagal",
                JOptionPane.WARNING_MESSAGE);
        }             // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jlebarppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlebarppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlebarppActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        float jari;
        jari=Integer.parseInt(jjari.getText());
        float hasil=(float) (4/3*3.14*jari*jari);
        try {
            JOptionPane.showMessageDialog(null,"Volume Bola Adalah :"+hasil,"volume",
                JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :"+e,"gagal",
                JOptionPane.WARNING_MESSAGE);
        }       // TODO         // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jjari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjari1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jjari1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        float jari,tinggi;
        
        jari=Integer.parseInt(jjari1.getText());
        tinggi=Integer.parseInt(jtinggi1.getText());
        float hasil=(float) (3.14*jari*jari*tinggi);
        try {
            JOptionPane.showMessageDialog(null,"Volume Tabung Adalah :"+hasil,"volume",
                JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :"+e,"gagal",
                JOptionPane.WARNING_MESSAGE);
        }                    // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jtinggi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtinggi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtinggi1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Volume ().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Volume ().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtinggippActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtinggippActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtinggippActionPerformed

    private void jpanjangpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpanjangpiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpanjangpiActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        float panjang,lebar,tinggi;
        panjang=Integer.parseInt(jpanjangpi.getText());
        lebar=Integer.parseInt(jlebarpi.getText());
        tinggi=Integer.parseInt(jtinggipi.getText());
        float hasil=(float) (panjang*lebar*tinggi/3);
        try {
            JOptionPane.showMessageDialog(null,"Volume Piramid Adalah :"+hasil,"volume",
                JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :"+e,"gagal",
                JOptionPane.WARNING_MESSAGE);
        }            // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jlebarpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlebarpiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlebarpiActionPerformed

    private void jtinggipiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtinggipiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtinggipiActionPerformed

    private void jpanjangprismaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpanjangprismaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpanjangprismaActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        float alas,tinggi,tp;
        alas=Integer.parseInt(jpanjangprisma.getText());
        tinggi=Integer.parseInt(jlebarprisma.getText());
        tp=Integer.parseInt(jtinggiprisma.getText());
        float hasil=(float) (alas*tinggi*tp/2);
        try {
            JOptionPane.showMessageDialog(null,"Volume Prisma Adalah :"+hasil,"volume",
                JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :"+e,"gagal",
                JOptionPane.WARNING_MESSAGE);
        }                  // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jlebarprismaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlebarprismaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlebarprismaActionPerformed

    private void jtinggiprismaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtinggiprismaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtinggiprismaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Volume().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane BOLA;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jjari;
    private javax.swing.JTextField jjari1;
    private javax.swing.JTextField jlebarpi;
    private javax.swing.JTextField jlebarpp;
    private javax.swing.JTextField jlebarprisma;
    private javax.swing.JTextField jpanjangpi;
    private javax.swing.JTextField jpanjangpp;
    private javax.swing.JTextField jpanjangprisma;
    private javax.swing.JTextField jsisi;
    private javax.swing.JTextField jtinggi1;
    private javax.swing.JTextField jtinggipi;
    private javax.swing.JTextField jtinggipp;
    private javax.swing.JTextField jtinggiprisma;
    // End of variables declaration//GEN-END:variables
}
